// ─────────────────────────────────────────────────────────────
// Domain model for Cibo — home food & pantry management
// ─────────────────────────────────────────────────────────────

export type StorageLocation = "fridge" | "freezer" | "pantry";

export type FoodCategory =
  | "produce"
  | "dairy"
  | "meat"
  | "fish"
  | "bakery"
  | "pantry"
  | "frozen"
  | "beverages"
  | "snacks"
  | "condiments"
  | "spices"
  | "other";

export type Unit =
  | "g"
  | "kg"
  | "ml"
  | "l"
  | "pcs"
  | "pack"
  | "can"
  | "bottle"
  | "slice"
  | "tbsp"
  | "tsp";

export interface Nutrition {
  kcal: number; // per 100g / 100ml / unit depending on basis
  protein: number;
  carbs: number;
  fat: number;
  fiber?: number;
  sugar?: number;
  salt?: number;
}

export type NutritionBasis = "per100g" | "perUnit";

export interface PantryItem {
  id: string;
  name: string;
  brand?: string;
  category: FoodCategory;
  location: StorageLocation;
  quantity: number;
  unit: Unit;
  initialQuantity: number;
  purchaseDate: string; // ISO
  expiryDate?: string; // ISO
  price?: number; // total paid
  barcode?: string;
  imageUrl?: string;
  nutrition?: Nutrition;
  nutritionBasis?: NutritionBasis;
  unitWeightG?: number; // grams per "pcs" for nutrition math
  allergens?: string[];
  opened?: boolean;
  openedDate?: string;
  store?: string;
  updatedAt: string;
}

export interface ShoppingItem {
  id: string;
  name: string;
  category: FoodCategory;
  quantity: number;
  unit: Unit;
  checked: boolean;
  auto: boolean; // generated by the app
  reason?: string; // why it was suggested
  estPrice?: number;
  createdAt: string;
}

export interface RecipeIngredient {
  name: string;
  quantity: number;
  unit: Unit;
  optional?: boolean;
}

export interface Recipe {
  id: string;
  title: string;
  description?: string;
  ingredients: RecipeIngredient[];
  steps: string[];
  minutes: number;
  difficulty: "easy" | "medium" | "hard";
  servings: number;
  nutrition: Nutrition; // per serving
  tags: string[];
  imageUrl?: string;
  source: "ai" | "user" | "seed";
  favorite?: boolean;
  createdAt: string;
}

export type MealType = "breakfast" | "lunch" | "dinner" | "snack";

export interface PlannedMeal {
  id: string;
  date: string; // YYYY-MM-DD
  meal: MealType;
  recipeId?: string;
  title: string;
  servings: number;
  nutrition?: Nutrition; // total for the entry
  cooked?: boolean;
}

export type WasteReason = "expired" | "spoiled" | "leftover" | "other";

export interface WasteLog {
  id: string;
  name: string;
  category: FoodCategory;
  quantity: number;
  unit: Unit;
  reason: WasteReason;
  estValue: number; // € lost
  co2: number; // kg CO2e
  date: string;
}

export interface ConsumptionLog {
  id: string;
  name: string;
  quantity: number;
  unit: Unit;
  nutrition?: Nutrition;
  savedValue?: number; // € of food used before expiry
  date: string;
}

export interface FamilyMember {
  id: string;
  name: string;
  color: string;
  role: "owner" | "member";
  email?: string;
}

export type Goal = "lose" | "maintain" | "gain" | "muscle";
export type Activity = "sedentary" | "light" | "moderate" | "active" | "athlete";
export type Sex = "male" | "female";

export interface DietProfile {
  name: string;
  sex: Sex;
  age: number;
  heightCm: number;
  weightKg: number;
  goal: Goal;
  activity: Activity;
  allergies: string[];
  preferences: string[]; // liked foods / cuisines
  dislikes: string[];
  diet?: "none" | "vegetarian" | "vegan" | "pescatarian" | "keto" | "mediterranean";
  // computed targets
  targetKcal?: number;
  targetProtein?: number;
  targetCarbs?: number;
  targetFat?: number;
}

export interface Settings {
  id: "app";
  theme: "light" | "dark" | "system";
  currency: string;
  notifExpiry: boolean;
  language: "it" | "en";
  onboarded: boolean;
}
